# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ironfish.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: typed[T] musings
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Thoughts about distribute, reactive and functional programming." # used by search engines

  # Header and footer text
  #  header_text: >
  #  header_text_feature_image:
  footer_text: >
   Copyright © 2014, 2015 Duncan K. DeVore. All rights reserved.

  # Icons
  rss: false
  email_address:
  github: ironfish
  twitter: ironfish
  linkedin: https://www.linkedin.com/in/duncandevore

  # Share links
  show_share: true

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: ironfish
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
